name: C/C++ CI

on:
  push:
#    branches: [ "chul" ]
#  pull_request:
#    branches: [ "chul" ]

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: cd
      run: cd ./source/adiabatic_spherical/
    - name: check
      run: ls
    # - name: make
    #   run: make
    # - name: make check
    #   run: ls 
#    - name: make adiabatic_spherical
#      run: ./source/adiabatic_spherical/make
