name: C/C++ CI

on:
  push:
    branches: chul

jobs:
  adiabatic_spherical:
    name: Run adiabatic_spherical
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: run adiabatic_spherical
      run: |
        pwd
        ./makecosmos.sh adiabatic_spherical
        cd ./adiabatic_spherical/
        make
        ./cosmos
        ls out_*

  scalar_iso:
    name: Run scalar_iso
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: run scalar_iso
      run: |
        pwd
        ./makecosmos.sh scalar_iso
        cd ./scalar_iso/
        make
        ./cosmos
        ls out_*

  sample_pert:
    name: Run sample_pert
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: run sample_pert
      run: |
        pwd
        ./makecosmos.sh sample_pert
        cd ./sample_pert/
        make
        ./cosmos
        ls out_*
